### PR TITLE
Remove references to namespace

### PR DESCRIPTION
**Pull request by csheremeta**

### CODE REVIEW

**Comment by jewzaam** [comment]
Context for this?  Is it so we manage the namespace in CI?  We could exclude the Namespace resource from the SSS and keep "namespace" in metadata.  This will make it easy to develop and not forget to change namespaces or use `-n`.

**Comment by csheremeta** [comment]
I'm working with Tejas on trying to determine ultimately whether this can be deployed through the app-SRE pipeline or not. He said I needed to remove all references to namespace from within this repo, and add a namespace file to app-interface, so we're testing that.

**Comment by jewzaam** [comment]
Expect the functional ask is to ensure pipelines create the namespace, not the template we provide.  Given this is a short lived thing (v3 only), is used in only a specific set of clusters, has a small scope for what it does, and is therefore unlikely to be manually deployed in the future for testing it should be OK.

/lgtm

**Comment by csheremeta** [comment]
Yes, that's the ask exactly

**Pull request merged**
